# I- Projet de business décisionnel  
## Analyse de la rentabilité d’un projet de vente

Ce notebook présente une analyse décisionnelle réalisée avant le lancement
d’un projet de vente de desserts faits maison.

## 1. Contexte du projet

Le projet consiste à vendre des desserts faits maison (cups et cookies)
pendant un mois précis, avec une production artisanale réalisée par une seule personne.

Les principales contraintes sont :
- le temps de production,
- la capacité limitée,
- la conservation courte des produits,
- des contraintes horaires variables.

## 2. Objectifs de l’analyse

Cette analyse vise à répondre aux questions suivantes :

- Quels produits sont les plus rentables ?
- Quel produit génère le plus de marge par heure de travail ?
- La box découverte est-elle pertinente économiquement ?
- Comment prioriser la production en cas de temps limité ?

Cette analyse repose sur plusieurs hypothèses simplificatrices :

- les coûts unitaires sont estimés et considérés comme constants,
- les temps de préparation sont des moyennes,
- la demande est supposée suffisante pour écouler la production,
- les coûts indirects (électricité, transport, communication) ne sont pas pris en compte.

Ces hypothèses permettent de se concentrer sur la rentabilité opérationnelle des produits.

In [5]:
import pandas as pd

## 3. Données utilisées

Les données utilisées dans ce projet sont des données construites,
basées sur des estimations réalistes de coûts, de temps de préparation
et de prix de vente.

In [8]:
df = pd.DataFrame({
    "id_produit": [1, 2, 3, 4, 5],
    "nom_produit": [
        "Strawberry Crunch Cup (moyenne)",
        "Strawberry Crunch Cup (grande)",
        "Cookie Crunch Cup",
        "Cookie Cup",
        "Box Découverte"
    ],
    "categorie": ["cup", "cup", "cookie", "cookie", "box"],
    "temps_preparation_min": [10, 10, 20, 15, 40],
    "cout_unitaire": [2.70, 3.85, 1.90, 1.40, 7.30],
    "prix_vente": [6.00, 8.00, 6.00, 4.00, 13.00]
})

## 4. Vérification des données

Avant toute analyse, il est important de vérifier que les données
ont bien été créées et qu’elles sont cohérentes.

In [7]:
df.head()

,id_produit,nom_produit,categorie,temps_preparation_min,cout_unitaire,prix_vente
0,1,Strawberry Crunch Cup (moyenne),cup,10,2.70,6.0
1,2,Strawberry Crunch Cup (grande),cup,10,3.85,8.0
2,3,Cookie Crunch Cup,cookie,20,1.90,6.0
3,4,Cookie Cup,cookie,15,1.40,4.0
4,5,Box Découverte,box,40,7.30,13.0

## 5. Calcul de la marge brute

La marge brute correspond à la différence entre le prix de vente
et le coût de production du produit.

Marge brute = Prix de vente − Coût unitaire

In [9]:
df["marge_brute"] = df["prix_vente"] - df["cout_unitaire"]
df

,id_produit,nom_produit,categorie,temps_preparation_min,cout_unitaire,prix_vente,marge_brute
0,1,Strawberry Crunch Cup (moyenne),cup,10,2.70,6.0,3.30
1,2,Strawberry Crunch Cup (grande),cup,10,3.85,8.0,4.15
2,3,Cookie Crunch Cup,cookie,20,1.90,6.0,4.10
3,4,Cookie Cup,cookie,15,1.40,4.0,2.60
4,5,Box Découverte,box,40,7.30,13.0,5.70

### Analyse de la marge brute

Les Strawberry Crunch Cups présentent une marge brute plus élevée que les cookies,
ce qui confirme leur rôle de produits principaux dans l’offre.

## 6. Calcul de la marge par minute

La marge par minute permet d’évaluer la rentabilité du temps passé
à produire un produit.

In [10]:
df["marge_par_minute"] = df["marge_brute"] / df["temps_preparation_min"]
df

,id_produit,nom_produit,categorie,temps_preparation_min,cout_unitaire,prix_vente,marge_brute,marge_par_minute
0,1,Strawberry Crunch Cup (moyenne),cup,10,2.70,6.0,3.30,0.330000
1,2,Strawberry Crunch Cup (grande),cup,10,3.85,8.0,4.15,0.415000
2,3,Cookie Crunch Cup,cookie,20,1.90,6.0,4.10,0.205000
3,4,Cookie Cup,cookie,15,1.40,4.0,2.60,0.173333
4,5,Box Découverte,box,40,7.30,13.0,5.70,0.142500

## 7. Calcul de la marge par heure

La marge par heure permet de comparer les produits entre eux
comme un revenu horaire.

In [11]:
df["marge_par_heure"] = df["marge_par_minute"] * 60
df

,id_produit,nom_produit,categorie,temps_preparation_min,cout_unitaire,prix_vente,marge_brute,marge_par_minute,marge_par_heure
0,1,Strawberry Crunch Cup (moyenne),cup,10,2.70,6.0,3.30,0.330000,19.80
1,2,Strawberry Crunch Cup (grande),cup,10,3.85,8.0,4.15,0.415000,24.90
2,3,Cookie Crunch Cup,cookie,20,1.90,6.0,4.10,0.205000,12.30
3,4,Cookie Cup,cookie,15,1.40,4.0,2.60,0.173333,10.40
4,5,Box Découverte,box,40,7.30,13.0,5.70,0.142500,8.55

### 8. Analyse de la marge par heure

La marge par heure met en évidence des différences importantes entre les produits.
Les Strawberry Crunch Cups génèrent la marge horaire la plus élevée.

Dans un contexte de production individuelle, cet indicateur est déterminant
pour prioriser les produits lorsque le temps est limité.

## 8. Analyse décisionnelle

À partir des indicateurs calculés, il est possible d’identifier
les produits les plus intéressants financièrement.

Cette analyse permet de :
- prioriser certains produits,
- justifier les choix de prix,
- limiter certains produits moins rentables.

In [12]:
df.sort_values(by="marge_par_heure", ascending=False)

,id_produit,nom_produit,categorie,temps_preparation_min,cout_unitaire,prix_vente,marge_brute,marge_par_minute,marge_par_heure
1,2,Strawberry Crunch Cup (grande),cup,10,3.85,8.0,4.15,0.415000,24.90
0,1,Strawberry Crunch Cup (moyenne),cup,10,2.70,6.0,3.30,0.330000,19.80
2,3,Cookie Crunch Cup,cookie,20,1.90,6.0,4.10,0.205000,12.30
3,4,Cookie Cup,cookie,15,1.40,4.0,2.60,0.173333,10.40
4,5,Box Découverte,box,40,7.30,13.0,5.70,0.142500,8.55

## 9. Simulation : production avec 2 heures disponibles

In [14]:
temps_disponible = 120  # minutes

df["quantite_possible"] = temps_disponible // df["temps_preparation_min"]
df["marge_totale_2h"] = df["quantite_possible"] * df["marge_brute"]

df[["nom_produit", "quantite_possible", "marge_totale_2h"]].sort_values(
    by="marge_totale_2h", ascending=False
)

                       nom_produit  quantite_possible  marge_totale_2h
1   Strawberry Crunch Cup (grande)                 12             49.8
0  Strawberry Crunch Cup (moyenne)                 12             39.6
2                Cookie Crunch Cup                  6             24.6
3                       Cookie Cup                  8             20.8
4                   Box Découverte                  3             17.1

### 10. Analyse de la simulation sur 2 heures

Cette simulation montre que, à temps de travail limité,
les Strawberry Crunch Cups génèrent la marge totale la plus élevée.
La box découverte, bien que rentable par unité, mobilise trop de temps
et réduit la marge totale réalisable sur une courte période.

Il est donc préférable de prioriser les produits à forte marge horaire
lorsque le temps de production est contraint.

## 11. Conclusion

À partir de cette analyse, il est recommandé de :
- prioriser la production des Strawberry Crunch Cups, plus rentables à l’heure,
- maintenir les cookies comme produits complémentaires,
- proposer la box découverte comme offre marketing plutôt que comme produit principal,
- adapter la production en fonction du temps disponible quotidiennement.